name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev/*]

jobs:
  test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:prod
      - run: npm run lint

  build:
    if: ${{ github.event_name == 'push' }}
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Building and Deploying...
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: production
          base_href: /bike-store/
          deploy_branch: master
          angular_dist_build_folder: dist/bike-store
